"""empty message

Revision ID: 1afbf52b9fc6
Revises: ec934a4155b8
Create Date: 2025-03-13 15:00:31.793121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1afbf52b9fc6'
down_revision = 'ec934a4155b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('purchase_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['purchase_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('purchase_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
