"""empty message

Revision ID: 4ee00e60ed59
Revises: d96ad43c0c8d
Create Date: 2025-03-13 13:49:54.088475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee00e60ed59'
down_revision = 'd96ad43c0c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'purchases', ['purchase_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('purchase_id')

    # ### end Alembic commands ###
