"""empty message

Revision ID: 7359e32c5660
Revises: 9570aae56ada
Create Date: 2025-03-12 02:14:08.800801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7359e32c5660'
down_revision = '9570aae56ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('descuento_aplicado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descuento_aplicado', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
