"""empty message

Revision ID: e858f7003638
Revises: 82e22debb6d4
Create Date: 2025-03-11 16:47:04.455691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e858f7003638'
down_revision = '82e22debb6d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('inventory_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('inventory_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
