"""empty message

Revision ID: ec934a4155b8
Revises: 99b7a00c52f3
Create Date: 2025-03-13 14:52:39.300649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec934a4155b8'
down_revision = '99b7a00c52f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint('invoices_purchase_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_unique_constraint('invoices_purchase_id_key', ['purchase_id'])

    # ### end Alembic commands ###
